In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
csv_file = "../Resources/world-happiness-report.csv"
world_happiness_report_df = pd.read_csv(csv_file)
world_happiness_report_df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [3]:
world_happiness_report_df=world_happiness_report_df[['Country name','Life Ladder','Log GDP per capita','Social support','Healthy life expectancy at birth','Freedom to make life choices','Generosity','Perceptions of corruption','year']]

In [4]:
world_happiness_report_df.head()

,Country name,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Afghanistan,3.724,7.370,0.451,50.80,0.718,0.168,0.882,2008
1,Afghanistan,4.402,7.540,0.552,51.20,0.679,0.190,0.850,2009
2,Afghanistan,4.758,7.647,0.539,51.60,0.600,0.121,0.707,2010
3,Afghanistan,3.832,7.620,0.521,51.92,0.496,0.162,0.731,2011
4,Afghanistan,3.783,7.705,0.521,52.24,0.531,0.236,0.776,2012

In [5]:
csv_file = "../Resources/world-happiness-report-2021.csv"
world_happiness_report_2021_df = pd.read_csv(csv_file)
world_happiness_report_2021_df.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.0,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.4,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798

In [6]:
world_happiness_report_2021_df=world_happiness_report_2021_df[['Country name','Ladder score','Logged GDP per capita','Social support','Healthy life expectancy','Freedom to make life choices','Generosity','Perceptions of corruption',]]

In [7]:
world_happiness_report_2021_df.head()

,Country name,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,7.842,10.775,0.954,72.0,0.949,-0.098,0.186
1,Denmark,7.620,10.933,0.954,72.7,0.946,0.030,0.179
2,Switzerland,7.571,11.117,0.942,74.4,0.919,0.025,0.292
3,Iceland,7.554,10.878,0.983,73.0,0.955,0.160,0.673
4,Netherlands,7.464,10.932,0.942,72.4,0.913,0.175,0.338

In [8]:
world_happiness_report_2021_df=world_happiness_report_2021_df.rename(columns={'Ladder score':'Life Ladder',
                                                                     'Logged GDP per capita':'Log GDP per capita',
                                                                     'Healthy life expectancy':'Healthy life expectancy at birth',
                                                                     })

In [9]:
world_happiness_report_2021_df.head()

,Country name,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,7.842,10.775,0.954,72.0,0.949,-0.098,0.186
1,Denmark,7.620,10.933,0.954,72.7,0.946,0.030,0.179
2,Switzerland,7.571,11.117,0.942,74.4,0.919,0.025,0.292
3,Iceland,7.554,10.878,0.983,73.0,0.955,0.160,0.673
4,Netherlands,7.464,10.932,0.942,72.4,0.913,0.175,0.338

In [10]:
world_happiness_report_2021_df['year']=2021

In [11]:
world_happiness_report_2021_df.head()

,Country name,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Finland,7.842,10.775,0.954,72.0,0.949,-0.098,0.186,2021
1,Denmark,7.620,10.933,0.954,72.7,0.946,0.030,0.179,2021
2,Switzerland,7.571,11.117,0.942,74.4,0.919,0.025,0.292,2021
3,Iceland,7.554,10.878,0.983,73.0,0.955,0.160,0.673,2021
4,Netherlands,7.464,10.932,0.942,72.4,0.913,0.175,0.338,2021

In [12]:
world_happiness_report_2021_df=world_happiness_report_2021_df.sort_values(by='Country name', ascending=True)

In [13]:
world_happiness_report_2021_df.head()

,Country name,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,year
148,Afghanistan,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,2021
92,Albania,5.117,9.520,0.697,68.999,0.785,-0.030,0.901,2021
108,Algeria,4.887,9.342,0.802,66.005,0.480,-0.067,0.752,2021
56,Argentina,5.929,9.962,0.898,69.000,0.828,-0.182,0.834,2021
85,Armenia,5.283,9.487,0.799,67.055,0.825,-0.168,0.629,2021

In [14]:
world_happiness_report_df.head()

,Country name,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Afghanistan,3.724,7.370,0.451,50.80,0.718,0.168,0.882,2008
1,Afghanistan,4.402,7.540,0.552,51.20,0.679,0.190,0.850,2009
2,Afghanistan,4.758,7.647,0.539,51.60,0.600,0.121,0.707,2010
3,Afghanistan,3.832,7.620,0.521,51.92,0.496,0.162,0.731,2011
4,Afghanistan,3.783,7.705,0.521,52.24,0.531,0.236,0.776,2012

In [15]:
world_happiness_report_2021_df=world_happiness_report_2021_df.rename(columns={'Country name':'country_name','Life Ladder':'Life_Ladder',
                                                                   'Log GDP per capita':'Log_GDP_per_capita',
                                                                   'Social support':'Social_support',
                                                                   'Healthy life expectancy at birth':'Healthy_life_expectancy_at_birth',
                                                                   'Freedom to make life choices':'Freedom_to_make_life_choices',
                                                                   'Perceptions of corruption':'Perceptions_of_corruption'                                                                
                                                                  })

In [16]:
world_happiness_report_df=world_happiness_report_df.rename(columns={'Country name':'country_name','Life Ladder':'Life_Ladder',
                                                                   'Log GDP per capita':'Log_GDP_per_capita',
                                                                   'Social support':'Social_support',
                                                                   'Healthy life expectancy at birth':'Healthy_life_expectancy_at_birth',
                                                                   'Freedom to make life choices':'Freedom_to_make_life_choices',
                                                                   'Perceptions of corruption':'Perceptions_of_corruption'                                                                
                                                                  })

In [17]:
world_happiness_report_df.head()

,country_name,Life_Ladder,Log_GDP_per_capita,Social_support,Healthy_life_expectancy_at_birth,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption,year
0,Afghanistan,3.724,7.370,0.451,50.80,0.718,0.168,0.882,2008
1,Afghanistan,4.402,7.540,0.552,51.20,0.679,0.190,0.850,2009
2,Afghanistan,4.758,7.647,0.539,51.60,0.600,0.121,0.707,2010
3,Afghanistan,3.832,7.620,0.521,51.92,0.496,0.162,0.731,2011
4,Afghanistan,3.783,7.705,0.521,52.24,0.531,0.236,0.776,2012

In [18]:
world_happiness_report_2021_df.head()

,country_name,Life_Ladder,Log_GDP_per_capita,Social_support,Healthy_life_expectancy_at_birth,Freedom_to_make_life_choices,Generosity,Perceptions_of_corruption,year
148,Afghanistan,2.523,7.695,0.463,52.493,0.382,-0.102,0.924,2021
92,Albania,5.117,9.520,0.697,68.999,0.785,-0.030,0.901,2021
108,Algeria,4.887,9.342,0.802,66.005,0.480,-0.067,0.752,2021
56,Argentina,5.929,9.962,0.898,69.000,0.828,-0.182,0.834,2021
85,Armenia,5.283,9.487,0.799,67.055,0.825,-0.168,0.629,2021

In [19]:
rds_connection_string = "postgres:postgres@localhost:5432/happiness_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [20]:
engine.table_names()

<ipython-input-20-d72bc75a6b62>:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

[]

In [21]:
world_happiness_report_df.to_sql(name='world_happiness_2008_2019', con=engine, if_exists='append', index=False)

In [22]:
world_happiness_report_2021_df.to_sql(name='world_happiness_2021', con=engine, if_exists='append', index=False)

In [ ]:
pd.read_sql_query('select * from world_happiness_2008_2019', con=engine).head()